apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - runtimeclass.yaml
  - rbac.yaml
  - networkpolicy.yaml
  - quota.yaml
  - postgres.yaml
  - platform.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: agentorch
